set(BUILD_SDL3      ON  CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_UTILS     OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS     OFF CACHE BOOL "" FORCE)
set(XNASONG         ON  CACHE BOOL "" FORCE)

add_subdirectory(${LIBS_DIR}/FAudio)
